#!/bin/sh
# Renders Formula/pgterm.rb for github.com/pgrundev/homebrew-tap from one
# release's checksums.txt. The release workflow runs this after the archives
# are published and pushes the result to the tap.
#
#   usage: packaging/homebrew/formula.sh <version> <checksums.txt>
#
# Homebrew fetches the archive for the host platform and verifies the pinned
# SHA-256 itself; the archive unpacks to a single directory, which Homebrew
# strips, leaving `pgterm` at the top level for bin.install.
set -eu

VERSION="$1"
SUMS="$2"
BASE="https://github.com/pgrundev/pgterm/releases/download/v${VERSION}"

sha() {
  s=$(grep " pgterm_${VERSION}_$1.tar.gz\$" "$SUMS" | cut -d' ' -f1)
  if [ -z "$s" ]; then
    echo "formula.sh: no checksum for pgterm_${VERSION}_$1.tar.gz in $SUMS" >&2
    exit 1
  fi
  printf '%s' "$s"
}

# Resolve every checksum before printing anything: a missing archive must
# fail the run (exit 1), not leak an empty sha256 into the formula.
DARWIN_AMD64=$(sha darwin_amd64)
DARWIN_ARM64=$(sha darwin_arm64)
LINUX_AMD64=$(sha linux_amd64)
LINUX_ARM64=$(sha linux_arm64)

cat <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by pgterm's release workflow (packaging/homebrew/formula.sh).
# DO NOT EDIT — the next release overwrites this file.
class Pgterm < Formula
  desc "Terminal UI that watches all your Postgres databases at once"
  homepage "https://pgterm.dev"
  version "${VERSION}"
  license "Apache-2.0"

  # No depends_on "pgrundev/tap/pgbot": Homebrew 6 trusts only the formula
  # named on the command line, so a dependency from the same third-party tap
  # is refused ("untrusted tap") for everyone who has not run brew trust.
  # pgbot is installed alongside instead (README) and named in caveats.

  on_macos do
    on_intel do
      url "${BASE}/pgterm_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
    on_arm do
      url "${BASE}/pgterm_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/pgterm_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
    on_arm do
      url "${BASE}/pgterm_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    bin.install "pgterm"
  end

  def caveats
    <<~EOS
      pgterm drives pgbot for every diagnostic. If pgbot is not on your PATH yet:
        brew install pgrundev/tap/pgbot
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pgterm --version")
  end
end
RUBY
